/**
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentMethodType.
* @enum {}
* @readonly
*/
export default class PaymentMethodType {
    
        /**
         * value: "CARD"
         * @const
         */
        "CARD" = "CARD";

    
        /**
         * value: "UPI"
         * @const
         */
        "UPI" = "UPI";

    

    /**
    * Returns a <code>PaymentMethodType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentMethodType} The enum <code>PaymentMethodType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

