/**
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PayoutListResponse from '../model/PayoutListResponse';
import PayoutResponse from '../model/PayoutResponse';

/**
* Payout service.
* @module api/PayoutApi
* @version 1.0.0
*/
export default class PayoutApi {

    /**
    * Constructs a new PayoutApi. 
    * @alias module:api/PayoutApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllPayouts operation.
     * @callback module:api/PayoutApi~getAllPayoutsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayoutListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All payouts
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.size 
     * @param {module:api/PayoutApi~getAllPayoutsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PayoutListResponse}
     */
    getAllPayouts(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayoutListResponse;
      return this.apiClient.callApi(
        '/payout', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPayoutByGid operation.
     * @callback module:api/PayoutApi~getPayoutByGidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayoutResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get payout by Gid
     * @param {String} gid 
     * @param {module:api/PayoutApi~getPayoutByGidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PayoutResponse}
     */
    getPayoutByGid(gid, callback) {
      let postBody = null;
      // verify the required parameter 'gid' is set
      if (gid === undefined || gid === null) {
        throw new Error("Missing the required parameter 'gid' when calling getPayoutByGid");
      }

      let pathParams = {
        'gid': gid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayoutResponse;
      return this.apiClient.callApi(
        '/payout/{gid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
