/**
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PlanListResponse from '../model/PlanListResponse';
import PlanRequest from '../model/PlanRequest';
import PlanResponse from '../model/PlanResponse';

/**
* Plan service.
* @module api/PlanApi
* @version 1.0.0
*/
export default class PlanApi {

    /**
    * Constructs a new PlanApi. 
    * @alias module:api/PlanApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addPlan operation.
     * @callback module:api/PlanApi~addPlanCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlanResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new plan
     * @param {module:model/PlanRequest} planRequest 
     * @param {module:api/PlanApi~addPlanCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlanResponse}
     */
    addPlan(planRequest, callback) {
      let postBody = planRequest;
      // verify the required parameter 'planRequest' is set
      if (planRequest === undefined || planRequest === null) {
        throw new Error("Missing the required parameter 'planRequest' when calling addPlan");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlanResponse;
      return this.apiClient.callApi(
        '/plan', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllPlan operation.
     * @callback module:api/PlanApi~getAllPlanCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlanListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Plan
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.size 
     * @param {String} opts.destinationAccount If processing on behalf of another Swirepay affiliate account
     * @param {module:api/PlanApi~getAllPlanCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlanListResponse}
     */
    getAllPlan(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'destination_account': opts['destinationAccount']
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlanListResponse;
      return this.apiClient.callApi(
        '/plan', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getplanByGid operation.
     * @callback module:api/PlanApi~getplanByGidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlanResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Plan by Gid
     * @param {String} gid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.destinationAccount If processing on behalf of another Swirepay affiliate account
     * @param {module:api/PlanApi~getplanByGidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlanResponse}
     */
    getplanByGid(gid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'gid' is set
      if (gid === undefined || gid === null) {
        throw new Error("Missing the required parameter 'gid' when calling getplanByGid");
      }

      let pathParams = {
        'gid': gid
      };
      let queryParams = {
      };
      let headerParams = {
        'destination_account': opts['destinationAccount']
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlanResponse;
      return this.apiClient.callApi(
        '/plan/{gid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePlan operation.
     * @callback module:api/PlanApi~updatePlanCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlanResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Plan
     * @param {String} gid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.destinationAccount If processing on behalf of another Swirepay affiliate account
     * @param {module:model/PlanRequest} opts.planRequest 
     * @param {module:api/PlanApi~updatePlanCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlanResponse}
     */
    updatePlan(gid, opts, callback) {
      opts = opts || {};
      let postBody = opts['planRequest'];
      // verify the required parameter 'gid' is set
      if (gid === undefined || gid === null) {
        throw new Error("Missing the required parameter 'gid' when calling updatePlan");
      }

      let pathParams = {
        'gid': gid
      };
      let queryParams = {
      };
      let headerParams = {
        'destination_account': opts['destinationAccount']
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlanResponse;
      return this.apiClient.callApi(
        '/plan/{gid}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
